# Generated by Django 4.0.3 on 2022-04-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_collect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagesLinks', models.ImageField(upload_to='images/')),
                ('his_tags', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
