# Generated by Django 4.0.3 on 2022-07-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_collect', '0002_imagesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagesReconnu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('pourcentage', models.IntegerField(null=True)),
                ('his_tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api_collect.tags')),
            ],
        ),
    ]
