# Generated by Django 3.2.8 on 2022-06-02 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='couleur_voiture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='marque_voiture',
        ),
        migrations.AlterField(
            model_name='code',
            name='heure',
            field=models.TimeField(verbose_name=datetime.datetime(2022, 6, 2, 15, 26, 24, 324981, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1),
        ),
    ]
