# Generated by Django 3.2.8 on 2022-06-16 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220602_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='heure',
            field=models.TimeField(verbose_name=datetime.datetime(2022, 6, 16, 7, 5, 43, 400347, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='genre',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1),
        ),
    ]
