# Generated by Django 3.2.8 on 2022-06-30 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220616_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='heure',
            field=models.TimeField(verbose_name=datetime.datetime(2022, 6, 30, 10, 47, 16, 716911, tzinfo=utc)),
        ),
    ]
