# Generated by Django 3.2.8 on 2022-06-30 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_code_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='heure',
            field=models.TimeField(verbose_name=datetime.datetime(2022, 6, 30, 11, 5, 28, 579067, tzinfo=utc)),
        ),
    ]
