# Generated by Django 3.2.8 on 2022-07-05 05:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_code_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='heure',
            field=models.TimeField(verbose_name=datetime.datetime(2022, 7, 5, 5, 44, 20, 876690, tzinfo=utc)),
        ),
    ]
