# Generated by Django 4.0.3 on 2022-07-05 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_code_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='heure',
            field=models.TimeField(verbose_name=datetime.datetime(2022, 7, 5, 9, 49, 30, 387175, tzinfo=utc)),
        ),
    ]
